import React, { Component } from "react";
import { Container, Header, Content, Accordion } from "native-base";
const dataArray = [
  { title: "Analytics and data mining to detect tax evasion", content: "Though Indian government has been machine learning and big data shy, it made an announcement of using data mining techniques to catch tax evaders in 2017 budget speech. The current numbers suggest that India is largely a tax non compliance society and government looked upon analytics as a way to nab tax evaders. Indian government rolled out new data analytics platform called Project Insight to catch tax evaders. It was announced that apart from traditional taxation data such as It return, IT form, TDS etc., it will rely on social media information. The algorithm would match spender patterns from these various sources with their declared income. Estimated to have cost around 10 billion rupees, it is expected to provide a non-intrusive information driven approach for improving tax compliance. Predictive analytics would enable authorities to predict the future of defaults and risks." },
  { title: "AI and data mining to track de-registered firms", content: "Using data mining government was able to gather information of 50,000 such entities that still existed despite being deregistered. Following the efforts on stopping the black money menace, names of more than 2.24 lakh companies have been struck off from the records and over 3 lakh directors were barred from directorship for their associations with such firms. Union minister P P Chaudhary admitted to a continued use of data mining with respect to struck off entities, adding that artificial intelligence could be used to identify illegal activities of companies." },
  { title: "Big Data approach on tracking the flow of goods", content: "One of the biggest uses of new age technologies by the government was the use of big data generated by GST network and railways to see the flow of goods within India. It released a survey that had first estimated the flow of goods across states within India, based on analysing transactions level data provided by the the Goods and Services Tax Network (GSTN). Chief Economic Advisor Arvind Subramanian was quoted as saying that the survey shows the first estimate of the flow of goods across states within India, based on analysing transactions level data provided by the Goods and Services Tax Network. It also studied the number of people that migrated every year within India." },
  { title: "Analytics in agriculture", content: "Technology has been looked upon by the government as a means to add to agriculture value chain and drive countless opportunities to make it a profitable industry. Big data was seen as the potential of adding value chain across each touch points starting from the selection of right agri-inputs, monitoring the soil moisture, controlling irrigations, and more. To keep a track of agricultural assets in the country, government also brought the idea of geotagging all agri-related infrastructure. The agriculture ministry has also signed a deal with the Indian Space Research Organisation (ISRO) to use satellites for mapping of assets." },
  { title: "Using big data to access public mood", content: "Back in 2016 it was reported that Prime Minister’s Office is using big data analytics to process citizen’s sentiments and ideas through the mygov.in crowdsourcing platform. According to reports, Modi government was making use of data analytics to filter and process all the key points that rise in debate on the platform and assess popular public mood about important issues from social media networking sites such as Facebook and Twitter. All the key findings were put together in special reports, along with concrete actionable measures. The fact that the website isn’t just mining out data but also transforming this data into actionable insights for helping out the Indian ministries, made it stand out amongst others." },
];
export default class Gov extends Component {
  static navigationOptions = ({navigation }) => ({
    title: "Governance",
      headerStyle: {
        backgroundColor: '#0da5ec', 
      },
      headerTitleStyle: {
        color: 'white'
      },
      headerTintColor: 'white'
  });

  render() {
    return (
      <Container>
        <Content padder>
          <Accordion
            dataArray={dataArray}
            headerStyle={{ backgroundColor: "#b7daf8" }}
            contentStyle={{ backgroundColor: "white" }}
          />
        </Content>
      </Container>
    );
  }
}